export enum EventType {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  SIMULATION_SUCCESS = 'SIMULATION_SUCCESS',
  SIMULATION_FAILED = 'SIMULATION_FAILED',
  SIMULATION_ERROR = 'SIMULATION_ERROR',
  FINALIZED = 'FINALIZED',
  ABANDONED = 'ABANDONED',
}
